In [123]:
import pandas as pd

df = pd.read_csv('promotions.csv')

## 01. Data Inspection

In [124]:
df.head(5)

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,NaN,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,NaN,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,NaN,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,NaN,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

In [125]:
df.describe()

       discount_value  stackable_flag  min_order_value
count       50.000000       50.000000        50.000000
mean        18.500000        0.240000     46000.000000
std         11.241777        0.431419     66116.779802
min         10.000000        0.000000         0.000000
25%         12.000000        0.000000         0.000000
50%         16.500000        0.000000         0.000000
75%         20.000000        0.000000    100000.000000
max         50.000000        1.000000    200000.000000

In [126]:
df.shape

(50, 10)

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   promo_id             50 non-null     object
 1   promo_name           50 non-null     object
 2   promo_type           50 non-null     object
 3   discount_value       50 non-null     float64
 4   start_date           50 non-null     object
 5   end_date             50 non-null     object
 6   applicable_category  10 non-null     object
 7   promo_channel        50 non-null     object
 8   stackable_flag       50 non-null     int64
 9   min_order_value      50 non-null     int64
dtypes: float64(1), int64(2), object(7)
memory usage: 4.0+ KB

## 02. Data Types

In [128]:
for col_name in df.columns:
    print(f"Column '{col_name}':")
    display(df[col_name].apply(type).value_counts())
    print("\n" + "-" * 30 + "\n")

Column 'promo_id':

promo_id
<class 'str'>    50
Name: count, dtype: int64

------------------------------

Column 'promo_name':

promo_name
<class 'str'>    50
Name: count, dtype: int64

------------------------------

Column 'promo_type':

promo_type
<class 'str'>    50
Name: count, dtype: int64

------------------------------

Column 'discount_value':

discount_value
<class 'float'>    50
Name: count, dtype: int64

------------------------------

Column 'start_date':

start_date
<class 'str'>    50
Name: count, dtype: int64

------------------------------

Column 'end_date':

end_date
<class 'str'>    50
Name: count, dtype: int64

------------------------------

Column 'applicable_category':

applicable_category
<class 'float'>    40
<class 'str'>      10
Name: count, dtype: int64

------------------------------

Column 'promo_channel':

promo_channel
<class 'str'>    50
Name: count, dtype: int64

------------------------------

Column 'stackable_flag':

stackable_flag
<class 'int'>    50
Name: count, dtype: int64

------------------------------

Column 'min_order_value':

min_order_value
<class 'int'>    50
Name: count, dtype: int64

------------------------------

## 03-Missing Values

In [129]:
df.isnull().sum()

promo_id                0
promo_name              0
promo_type              0
discount_value          0
start_date              0
end_date                0
applicable_category    40
promo_channel           0
stackable_flag          0
min_order_value         0
dtype: int64

In [130]:
df.isna().sum()

promo_id                0
promo_name              0
promo_type              0
discount_value          0
start_date              0
end_date                0
applicable_category    40
promo_channel           0
stackable_flag          0
min_order_value         0
dtype: int64

In [131]:
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [promo_id, promo_name, promo_type, discount_value, start_date, end_date, applicable_category, promo_channel, stackable_flag, min_order_value]
Index: []

In [132]:
# applicable_category có 80% giá trị bị thiếu (40/50 dòng). Do tỷ lệ thiếu cao và không đủ thông tin
# để thay thế một cách đáng tin cậy, cột được loại bỏ khỏi dataset.
df['applicable_category'] = df['applicable_category'].fillna('Unkown')

In [133]:
df.isnull().sum()

promo_id               0
promo_name             0
promo_type             0
discount_value         0
start_date             0
end_date               0
applicable_category    0
promo_channel          0
stackable_flag         0
min_order_value        0
dtype: int64

## 04 - Duplicates & Invalid Data

In [134]:
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [promo_id, promo_name, promo_type, discount_value, start_date, end_date, applicable_category, promo_channel, stackable_flag, min_order_value]
Index: []

In [135]:
df.head(5)

,promo_id,promo_name,promo_type,discount_value,start_date,end_date,applicable_category,promo_channel,stackable_flag,min_order_value
0,PROMO-0001,Spring Sale 2013,percentage,12.0,2013-03-18,2013-04-17,Unkown,email,1,0
1,PROMO-0002,Mid-Year Sale 2013,percentage,18.0,2013-06-23,2013-07-22,Unkown,online,0,0
2,PROMO-0003,Fall Launch 2013,percentage,10.0,2013-08-30,2013-10-02,Unkown,email,0,0
3,PROMO-0004,Year-End Sale 2013,percentage,20.0,2013-11-18,2014-01-02,Unkown,all_channels,0,50000
4,PROMO-0005,Urban Blowout 2013,fixed,50.0,2013-07-30,2013-09-02,Streetwear,online,0,150000

In [136]:
df.duplicated(subset=['promo_id']).sum()

df.duplicated(subset=['promo_name']).sum()

np.int64(0)

In [137]:
df[df['discount_value'] < 0].sum()
df[df['min_order_value'] < 0].sum()

promo_id                 0
promo_name               0
promo_type               0
discount_value         0.0
start_date               0
end_date                 0
applicable_category      0
promo_channel            0
stackable_flag           0
min_order_value          0
dtype: object

### Kiểm tra các dòng có `start_date` lớn hơn `end_date`

In [138]:
#Kiem tra ngay bat dau < ngay ket thuc
df['start_date'] = pd.to_datetime(df['start_date'])
df['end_date'] = pd.to_datetime(df['end_date'])

invalid_date_range = df[df['start_date'] > df['end_date']]
display(invalid_date_range)

Empty DataFrame
Columns: [promo_id, promo_name, promo_type, discount_value, start_date, end_date, applicable_category, promo_channel, stackable_flag, min_order_value]
Index: []

In [139]:
df['promo_channel'].value_counts()

promo_channel
all_channels    19
online          13
email            7
social_media     6
in_store         5
Name: count, dtype: int64

In [140]:
before = df['promo_name'].nunique()
after = df['promo_name'].str.strip().str.lower().nunique()

if before != after:
    print(f"Có vấn đề: {before} giá trị unique -> còn {after} sau khi chuẩn hóa")
else:
    print("Không phát hiện khoảng trắng/viết hoa thừa")

Không phát hiện khoảng trắng/viết hoa thừa

In [141]:
df['stackable_flag'].value_counts()
#Khong co gia tri la

stackable_flag
0    38
1    12
Name: count, dtype: int64

##  05 - Outliers

In [142]:
df['discount_value'].describe()
# Khong co dau hieu bat thường

count    50.000000
mean     18.500000
std      11.241777
min      10.000000
25%      12.000000
50%      16.500000
75%      20.000000
max      50.000000
Name: discount_value, dtype: float64

In [143]:
df['min_order_value'].describe()
#Bat thuong tuy nhien, day la gia tri toi thieu can ktr them

count        50.000000
mean      46000.000000
std       66116.779802
min           0.000000
25%           0.000000
50%           0.000000
75%      100000.000000
max      200000.000000
Name: min_order_value, dtype: float64

In [144]:
# Xem phân bố cụ thể — bao nhiêu dòng có giá trị 0
print(df['min_order_value'].value_counts().sort_index())

# Xem % dòng = 0
print((df['min_order_value'] == 0).mean() * 100, "%")

min_order_value
0         31
50000      4
100000     5
150000     8
200000     2
Name: count, dtype: int64
62.0 %

In [145]:
print("Giá trị âm:", (df['min_order_value'] < 0).sum())

Q1 = df['min_order_value'].quantile(0.25)
Q3 = df['min_order_value'].quantile(0.75)
IQR = Q3 - Q1
upper = Q3 + 1.5 * IQR
print("Ngưỡng trên (IQR):", upper)
print("Số dòng vượt ngưỡng:", (df['min_order_value'] > upper).sum())

Giá trị âm: 0
Ngưỡng trên (IQR): 250000.0
Số dòng vượt ngưỡng: 0

In [146]:
df.to_csv('promotions_cleaned.csv', index=False)